// <auto-generated />
using System;
using FootballRefereeManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballRefereeManagementSystem.Data.Migrations
{
    [DbContext(typeof(FootballRefereeManagementSystemDbContext))]
    [Migration("20230704192308_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovedForReferee")
                        .HasColumnType("bit")
                        .HasComment("Whether user has been approved to become referee");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("RefereeId")
                        .HasColumnType("int")
                        .HasComment("The navigation to the referee for this user");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasComment("Customization of Default Identity User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea01fe26-36c8-4daa-b1c8-8b9209e82478"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "463c400f-230d-4813-89ee-7487bec51d33",
                            Email = "referee@bfs.com",
                            EmailConfirmed = false,
                            IsApprovedForReferee = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "REFEREE@BFS.COM",
                            NormalizedUserName = "REFEREE@BFS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBF/gi3lGCp4LkxFwz75FYa6k+VOQUHzVjJ577iowrvFvHRZlZjHRSeaNX+SEOf/cw==",
                            PhoneNumberConfirmed = false,
                            RefereeId = 1,
                            SecurityStamp = "e1772a57-1957-44cc-97d5-3c8e170b411f",
                            TwoFactorEnabled = false,
                            UserName = "referee@bfs.com"
                        },
                        new
                        {
                            Id = new Guid("1e48bbc8-cbf0-494c-89e0-6bcccc36cc6a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "58ed9764-56cc-4680-b9bc-af7a5b11599a",
                            Email = "assitant_referee1@bfs.com",
                            EmailConfirmed = false,
                            IsApprovedForReferee = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ASSITANT_REFEREE1@BFS.COM",
                            NormalizedUserName = "ASSITANT_REFEREE1@BFS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGJjdq9d7AgEM7VCSVstG7hQZqxF2zD14p06H8SAKCvTZQ3PAlADFkZRAwY6Zmz52Q==",
                            PhoneNumberConfirmed = false,
                            RefereeId = 2,
                            SecurityStamp = "f2a6f49d-e069-4633-93d2-c977ce283ea0",
                            TwoFactorEnabled = false,
                            UserName = "assitant_referee1@bfs.com"
                        },
                        new
                        {
                            Id = new Guid("065a8654-fc52-43b4-8d3d-7e90a87e2bd9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74c835d7-2f5a-43f4-812d-4b935b19950b",
                            Email = "assitant_referee2@bfs.com",
                            EmailConfirmed = false,
                            IsApprovedForReferee = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ASSITANT_REFEREE2@BFS.COM",
                            NormalizedUserName = "ASSITANT_REFEREE2@BFS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFqmUmIrmgeJEWZb4G9iYZtvxiszEyVvlb8aF3Hv3bY4XvFSXeRoxTM44EkrfvS5lA==",
                            PhoneNumberConfirmed = false,
                            RefereeId = 3,
                            SecurityStamp = "7b7facd1-3ed7-4d6f-99b6-92bfddd2a150",
                            TwoFactorEnabled = false,
                            UserName = "assitant_referee2@bfs.com"
                        },
                        new
                        {
                            Id = new Guid("35e56d1c-a7c2-445d-9eb5-0cdaecb0ebb1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79f39826-6bff-465b-8b33-d463539f9351",
                            Email = "delegate@bfs.com",
                            EmailConfirmed = false,
                            IsApprovedForReferee = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DELEGATE@BFS.COM",
                            NormalizedUserName = "DELEGATE@BFS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJR5ft+CjBSGJp3dtPXr6Ra2tgmpAmJUh+sQzKqw3Iaywyk8YMXgCymxDIMmIdZAlw==",
                            PhoneNumberConfirmed = false,
                            RefereeId = 4,
                            SecurityStamp = "4b56621d-32f1-47f9-8823-aa0fec847952",
                            TwoFactorEnabled = false,
                            UserName = "delegate@bfs.com"
                        },
                        new
                        {
                            Id = new Guid("d9f18631-5bdb-4b41-86f4-8d6dbe71efb6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7dce1744-5c00-4f5b-9772-f88870fbe22e",
                            Email = "admin@bfs.com",
                            EmailConfirmed = false,
                            IsApprovedForReferee = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BFS.COM",
                            NormalizedUserName = "ADMIN@BFS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENFqhUSSHssUZMlhzWdje/quzdqhjO1uAWBAkAAoXh9WLXpIVg2GLeOW8qIAZYAUFw==",
                            PhoneNumberConfirmed = false,
                            RefereeId = 5,
                            SecurityStamp = "12c231e6-8ae9-4444-8aaf-e71ad9f1b339",
                            TwoFactorEnabled = false,
                            UserName = "admin@bfs.com"
                        },
                        new
                        {
                            Id = new Guid("625400fd-3a0d-4e0a-98a3-81590eb56816"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13b6049c-7581-481d-a320-3fe29918fa8d",
                            Email = "random_person@gmail.com",
                            EmailConfirmed = false,
                            IsApprovedForReferee = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "RANDOM_PERSON@GMAIL.COM",
                            NormalizedUserName = "RANDOM_PERSON@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMUavFCH9PnQDRDVdxxxNOOGvENQj34M+YYvGlwMQhvI76oZD5VpOT47cNmGxiHUrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "945fd909-a485-43a6-ad33-63c7d5f4e701",
                            TwoFactorEnabled = false,
                            UserName = "random_person@gmail.com"
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Division name");

                    b.HasKey("Id");

                    b.ToTable("Divisions");

                    b.HasComment("Division represents the level of the teams playing in it");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Първа професионална футболна лига"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Втора професионална футболна лига"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Трета аматьорска футболна лига"
                        },
                        new
                        {
                            Id = 4,
                            Name = "„А“ областнa футболнa групa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "„Б“ областнa футболнa групa"
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Age of the person represented by this entity");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("First name of the person represented by this entity");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Last name of the person represented by this entity");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasComment("Manager is the one who is in charge of team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 56,
                            FirstName = "Янко",
                            LastName = "Павлов"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            FirstName = "Димитър",
                            LastName = "Стефанов"
                        },
                        new
                        {
                            Id = 3,
                            Age = 62,
                            FirstName = "Михаил",
                            LastName = "Симеонов"
                        },
                        new
                        {
                            Id = 4,
                            Age = 36,
                            FirstName = "Михаел",
                            LastName = "Димов"
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int")
                        .HasComment("Information about guest team");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasComment("In what division is the match played");

                    b.Property<string>("FinalResult")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("The final result of the match");

                    b.Property<DateTime>("FixtureTime")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time the match is played");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int")
                        .HasComment("Information about host team");

                    b.Property<Guid?>("RefereeSquadId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The referee squad appointed to officiate the match");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasComment("Season during which match takes place");

                    b.Property<int>("TownId")
                        .HasColumnType("int")
                        .HasComment("Town in which the match is played");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("TownId");

                    b.HasIndex("AwayTeamId", "SeasonId");

                    b.HasIndex("HomeTeamId", "SeasonId");

                    b.ToTable("Matches");

                    b.HasComment("Information about a football match");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 9, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            RefereeSquadId = new Guid("5f7a5bad-da9c-4fd9-871a-483492e9bdaa"),
                            SeasonId = 1,
                            TownId = 2
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 3,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 9, 24, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            SeasonId = 1,
                            TownId = 2
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 4,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 10, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            SeasonId = 1,
                            TownId = 2
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 1,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 10, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            SeasonId = 1,
                            TownId = 3
                        },
                        new
                        {
                            Id = 5,
                            AwayTeamId = 3,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 9, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            SeasonId = 1,
                            TownId = 3
                        },
                        new
                        {
                            Id = 6,
                            AwayTeamId = 4,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 9, 18, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            SeasonId = 1,
                            TownId = 3
                        },
                        new
                        {
                            Id = 7,
                            AwayTeamId = 1,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 10, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            SeasonId = 1,
                            TownId = 4
                        },
                        new
                        {
                            Id = 8,
                            AwayTeamId = 2,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 10, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            SeasonId = 1,
                            TownId = 4
                        },
                        new
                        {
                            Id = 9,
                            AwayTeamId = 4,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 9, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            SeasonId = 1,
                            TownId = 4
                        },
                        new
                        {
                            Id = 10,
                            AwayTeamId = 1,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 9, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 4,
                            SeasonId = 1,
                            TownId = 5
                        },
                        new
                        {
                            Id = 11,
                            AwayTeamId = 2,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 9, 24, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 4,
                            SeasonId = 1,
                            TownId = 5
                        },
                        new
                        {
                            Id = 12,
                            AwayTeamId = 3,
                            DivisionId = 4,
                            FixtureTime = new DateTime(2022, 10, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 4,
                            SeasonId = 1,
                            TownId = 5
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasComment("Referee who created the message");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("The content of the message");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Time and date of creation");

                    b.Property<Guid>("RefereeSquadId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The match center where comment was made");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RefereeSquadId");

                    b.ToTable("Messages");

                    b.HasComment("Messages the referee write in match center");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Age of the player");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("First name of the player");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Last name of the player");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("In what position the player plays in the team");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasComment("Player playing in specific team during specific season");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            FirstName = "Емил",
                            LastName = "Иванов"
                        },
                        new
                        {
                            Id = 2,
                            Age = 16,
                            FirstName = "Илия",
                            LastName = "Даниелов"
                        },
                        new
                        {
                            Id = 3,
                            Age = 15,
                            FirstName = "Антон",
                            LastName = "Георгиев"
                        },
                        new
                        {
                            Id = 4,
                            Age = 17,
                            FirstName = "Борислав",
                            LastName = "Павлов"
                        },
                        new
                        {
                            Id = 5,
                            Age = 36,
                            FirstName = "Тодор",
                            LastName = "Николов"
                        },
                        new
                        {
                            Id = 6,
                            Age = 37,
                            FirstName = "Владимир",
                            LastName = "Георгиев"
                        },
                        new
                        {
                            Id = 7,
                            Age = 34,
                            FirstName = "Михаел",
                            LastName = "Калоянов"
                        },
                        new
                        {
                            Id = 8,
                            Age = 24,
                            FirstName = "Георгиос",
                            LastName = "Илиев"
                        },
                        new
                        {
                            Id = 9,
                            Age = 20,
                            FirstName = "Румен",
                            LastName = "Мартинов"
                        },
                        new
                        {
                            Id = 10,
                            Age = 24,
                            FirstName = "Алексей",
                            LastName = "Стефанов"
                        },
                        new
                        {
                            Id = 11,
                            Age = 27,
                            FirstName = "Виктор",
                            LastName = "Руменов"
                        },
                        new
                        {
                            Id = 12,
                            Age = 36,
                            FirstName = "Никола",
                            LastName = "Мартинов"
                        },
                        new
                        {
                            Id = 13,
                            Age = 23,
                            FirstName = "Георгиос",
                            LastName = "Илиев"
                        },
                        new
                        {
                            Id = 14,
                            Age = 22,
                            FirstName = "Димо",
                            LastName = "Габриелов"
                        },
                        new
                        {
                            Id = 15,
                            Age = 26,
                            FirstName = "Антонио",
                            LastName = "Янков"
                        },
                        new
                        {
                            Id = 16,
                            Age = 27,
                            FirstName = "Стефано",
                            LastName = "Борисов"
                        },
                        new
                        {
                            Id = 17,
                            Age = 35,
                            FirstName = "Андрей",
                            LastName = "Георгиев"
                        },
                        new
                        {
                            Id = 18,
                            Age = 23,
                            FirstName = "Андрей",
                            LastName = "Габриелов"
                        },
                        new
                        {
                            Id = 19,
                            Age = 34,
                            FirstName = "Андрей",
                            LastName = "Ивайлов"
                        },
                        new
                        {
                            Id = 20,
                            Age = 36,
                            FirstName = "Иво",
                            LastName = "Максимов"
                        },
                        new
                        {
                            Id = 21,
                            Age = 30,
                            FirstName = "Роберт",
                            LastName = "Ивов"
                        },
                        new
                        {
                            Id = 22,
                            Age = 33,
                            FirstName = "Мартин",
                            LastName = "Петров"
                        },
                        new
                        {
                            Id = 23,
                            Age = 35,
                            FirstName = "Християн",
                            LastName = "Алексеев"
                        },
                        new
                        {
                            Id = 24,
                            Age = 33,
                            FirstName = "Емил",
                            LastName = "Димитров"
                        },
                        new
                        {
                            Id = 25,
                            Age = 28,
                            FirstName = "Марио",
                            LastName = "Георгиев"
                        },
                        new
                        {
                            Id = 26,
                            Age = 26,
                            FirstName = "Михаил",
                            LastName = "Стефаносов"
                        },
                        new
                        {
                            Id = 27,
                            Age = 20,
                            FirstName = "Мартин",
                            LastName = "Илиев"
                        },
                        new
                        {
                            Id = 28,
                            Age = 14,
                            FirstName = "Радослав",
                            LastName = "Николов"
                        },
                        new
                        {
                            Id = 29,
                            Age = 22,
                            FirstName = "Калоян",
                            LastName = "Велинов"
                        },
                        new
                        {
                            Id = 30,
                            Age = 28,
                            FirstName = "Георги",
                            LastName = "Владимиров"
                        },
                        new
                        {
                            Id = 31,
                            Age = 24,
                            FirstName = "Любомир",
                            LastName = "Ивайлов"
                        },
                        new
                        {
                            Id = 32,
                            Age = 34,
                            FirstName = "Георги",
                            LastName = "Кристиянов"
                        },
                        new
                        {
                            Id = 33,
                            Age = 35,
                            FirstName = "Борислав",
                            LastName = "Павлов"
                        },
                        new
                        {
                            Id = 34,
                            Age = 21,
                            FirstName = "Иво",
                            LastName = "Василев"
                        },
                        new
                        {
                            Id = 35,
                            Age = 23,
                            FirstName = "Александър",
                            LastName = "Робертов"
                        },
                        new
                        {
                            Id = 36,
                            Age = 17,
                            FirstName = "Георгиос",
                            LastName = "Николов"
                        },
                        new
                        {
                            Id = 37,
                            Age = 34,
                            FirstName = "Васил",
                            LastName = "Владимиров"
                        },
                        new
                        {
                            Id = 38,
                            Age = 21,
                            FirstName = "Румен",
                            LastName = "Петров"
                        },
                        new
                        {
                            Id = 39,
                            Age = 28,
                            FirstName = "Марин",
                            LastName = "Мартинов"
                        },
                        new
                        {
                            Id = 40,
                            Age = 28,
                            FirstName = "Любен",
                            LastName = "Николов"
                        },
                        new
                        {
                            Id = 41,
                            Age = 28,
                            FirstName = "Радослав",
                            LastName = "Георгиев"
                        },
                        new
                        {
                            Id = 42,
                            Age = 25,
                            FirstName = "Николай",
                            LastName = "Николов"
                        },
                        new
                        {
                            Id = 43,
                            Age = 25,
                            FirstName = "Марин",
                            LastName = "Радославов"
                        },
                        new
                        {
                            Id = 44,
                            Age = 35,
                            FirstName = "Иван",
                            LastName = "Георгиев"
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.PlayerTeamSeason", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasComment("Team playing in specific season");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasComment("The player in the team");

                    b.HasKey("TeamId", "SeasonId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerTeamSeason");

                    b.HasComment("Player playing in a team during a season");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 1
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 2
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 3
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 4
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 5
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 6
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 7
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 8
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 9
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 10
                        },
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            PlayerId = 11
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 12
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 13
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 14
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 15
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 16
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 17
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 18
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 19
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 20
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 21
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            PlayerId = 22
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 23
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 24
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 25
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 26
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 27
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 28
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 29
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 30
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 31
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 32
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            PlayerId = 33
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 34
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 35
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 36
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 37
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 38
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 39
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 40
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 41
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 42
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 43
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            PlayerId = 44
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Referee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Age of the person represented by this entity");

                    b.Property<DateTime>("CareerStart")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of registration within the organization");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Phone number of the person represented by this entity");

                    b.Property<int>("CurrentlyAppointedMatchesCount")
                        .HasColumnType("int")
                        .HasComment("The number of matches appointed to this entity on current round");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("First name of the person represented by this entity");

                    b.Property<string>("ImageUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("~/Images/Referees/referee-default-avatar.png")
                        .HasComment("Picture of the person represented by this entity");

                    b.Property<bool>("IsAvaliable")
                        .HasColumnType("bit")
                        .HasComment("Gives information if person is free to officiate matches for current round");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Last name of the person represented by this entity");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasComment("Current role of the person represented by this entity within the organization");

                    b.Property<int>("TotalMatchesOfficiated")
                        .HasColumnType("int")
                        .HasComment("Number of matches officiated");

                    b.Property<int>("TownId")
                        .HasColumnType("int")
                        .HasComment("Current town which the person represented by this entity resides");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The registered user related to this entity");

                    b.HasKey("Id");

                    b.HasIndex("TownId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Referees");

                    b.HasComment("The main entity of the application");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 46,
                            CareerStart = new DateTime(2017, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Contact = "0981899391",
                            CurrentlyAppointedMatchesCount = 0,
                            FirstName = "Янко",
                            IsAvaliable = true,
                            LastName = "Христов",
                            Role = 0,
                            TotalMatchesOfficiated = 0,
                            TownId = 1,
                            UserId = new Guid("ea01fe26-36c8-4daa-b1c8-8b9209e82478")
                        },
                        new
                        {
                            Id = 2,
                            Age = 29,
                            CareerStart = new DateTime(2022, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Contact = "0962329705",
                            CurrentlyAppointedMatchesCount = 0,
                            FirstName = "Марин",
                            IsAvaliable = true,
                            LastName = "Радославов",
                            Role = 1,
                            TotalMatchesOfficiated = 0,
                            TownId = 1,
                            UserId = new Guid("1e48bbc8-cbf0-494c-89e0-6bcccc36cc6a")
                        },
                        new
                        {
                            Id = 3,
                            Age = 53,
                            CareerStart = new DateTime(2021, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Contact = "0991130099",
                            CurrentlyAppointedMatchesCount = 0,
                            FirstName = "Петър",
                            IsAvaliable = true,
                            LastName = "Николов",
                            Role = 1,
                            TotalMatchesOfficiated = 0,
                            TownId = 1,
                            UserId = new Guid("065a8654-fc52-43b4-8d3d-7e90a87e2bd9")
                        },
                        new
                        {
                            Id = 4,
                            Age = 33,
                            CareerStart = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Contact = "0962607874",
                            CurrentlyAppointedMatchesCount = 0,
                            FirstName = "Никола",
                            IsAvaliable = true,
                            LastName = "Антонов",
                            Role = 2,
                            TotalMatchesOfficiated = 0,
                            TownId = 1,
                            UserId = new Guid("35e56d1c-a7c2-445d-9eb5-0cdaecb0ebb1")
                        },
                        new
                        {
                            Id = 5,
                            Age = 19,
                            CareerStart = new DateTime(2019, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Contact = "0875267481",
                            CurrentlyAppointedMatchesCount = 0,
                            FirstName = "Симеон",
                            IsAvaliable = false,
                            LastName = "Радославов",
                            Role = 3,
                            TotalMatchesOfficiated = 0,
                            TownId = 1,
                            UserId = new Guid("d9f18631-5bdb-4b41-86f4-8d6dbe71efb6")
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.RefereeDivision", b =>
                {
                    b.Property<int>("RefereeId")
                        .HasColumnType("int")
                        .HasComment("Referee in specific division");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasComment("Division in which referee is allowed to offciate");

                    b.Property<int>("DivisionMatchesOfficiated")
                        .HasColumnType("int")
                        .HasComment("The count of matches referee officiated in this division");

                    b.HasKey("RefereeId", "DivisionId");

                    b.HasIndex("DivisionId");

                    b.ToTable("RefereesDivisions");

                    b.HasComment("Mapping table for Referee and Division");

                    b.HasData(
                        new
                        {
                            RefereeId = 1,
                            DivisionId = 5,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 1,
                            DivisionId = 4,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 2,
                            DivisionId = 5,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 2,
                            DivisionId = 4,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 3,
                            DivisionId = 5,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 3,
                            DivisionId = 4,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 4,
                            DivisionId = 5,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 4,
                            DivisionId = 4,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 4,
                            DivisionId = 3,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 5,
                            DivisionId = 2,
                            DivisionMatchesOfficiated = 0
                        },
                        new
                        {
                            RefereeId = 5,
                            DivisionId = 1,
                            DivisionMatchesOfficiated = 0
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.RefereeSquad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key");

                    b.Property<int>("DelegateId")
                        .HasColumnType("int")
                        .HasComment("Delegate who will supervise the officials");

                    b.Property<int>("FirstAssistantRefereeId")
                        .HasColumnType("int")
                        .HasComment("First assistant of the match");

                    b.Property<int>("MainRefereeId")
                        .HasColumnType("int")
                        .HasComment("Main referee of the squad");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasComment("Match assigned to the squad");

                    b.Property<int>("SecondAssistantRefereeId")
                        .HasColumnType("int")
                        .HasComment("Second assistant of the match");

                    b.HasKey("Id");

                    b.HasIndex("DelegateId");

                    b.HasIndex("FirstAssistantRefereeId");

                    b.HasIndex("MainRefereeId");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("SecondAssistantRefereeId");

                    b.ToTable("RefereesSquads");

                    b.HasComment("Every referee squad consists of 1 main ref, 2 assitants and a delegate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f7a5bad-da9c-4fd9-871a-483492e9bdaa"),
                            DelegateId = 4,
                            FirstAssistantRefereeId = 2,
                            MainRefereeId = 1,
                            MatchId = 1,
                            SecondAssistantRefereeId = 3
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasComment("Short name for the season (e.g. 2004/05, 2011/12, 2022/23)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2")
                        .HasComment("End of the season");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2")
                        .HasComment("Start of the season");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasComment("Season is the timespan in which all matches between teams are played");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "2022/23",
                            End = new DateTime(2023, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2022, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasComment("Abbreviation of the team");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the team");

                    b.Property<int>("TownId")
                        .HasColumnType("int")
                        .HasComment("In which town the team is located");

                    b.HasKey("Id");

                    b.HasIndex("TownId");

                    b.ToTable("Teams");

                    b.HasComment("Team that plays matches in specific division during specific season");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "БТВ",
                            Name = "Ботев",
                            TownId = 2
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "ВИХР",
                            Name = "Вихър",
                            TownId = 3
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "ГГНТ",
                            Name = "Гигант",
                            TownId = 4
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "КМОС",
                            Name = "Космос",
                            TownId = 5
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.TeamSeason", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasComment("Team that participates specific season");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasComment("The specific season");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasComment("In which division the team plays");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasComment("The manager of the team for specific season");

                    b.Property<int>("Placement")
                        .HasColumnType("int")
                        .HasComment("Placement in the division during the season");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasComment("Points earned during season");

                    b.Property<int>("ShirtColor")
                        .HasColumnType("int")
                        .HasComment("Color of the player's shirts");

                    b.HasKey("TeamId", "SeasonId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("SeasonId");

                    b.ToTable("TeamsSeasons");

                    b.HasComment("Mapping table for team and season");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            SeasonId = 1,
                            DivisionId = 4,
                            ManagerId = 1,
                            Placement = 1,
                            Points = 0,
                            ShirtColor = 11
                        },
                        new
                        {
                            TeamId = 2,
                            SeasonId = 1,
                            DivisionId = 4,
                            ManagerId = 2,
                            Placement = 1,
                            Points = 0,
                            ShirtColor = 0
                        },
                        new
                        {
                            TeamId = 3,
                            SeasonId = 1,
                            DivisionId = 4,
                            ManagerId = 3,
                            Placement = 1,
                            Points = 0,
                            ShirtColor = 4
                        },
                        new
                        {
                            TeamId = 4,
                            SeasonId = 1,
                            DivisionId = 4,
                            ManagerId = 4,
                            Placement = 1,
                            Points = 0,
                            ShirtColor = 2
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Distance")
                        .HasColumnType("float")
                        .HasComment("Distance to town from given location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)")
                        .HasComment("Name of the town");

                    b.Property<double>("TravelCost")
                        .HasColumnType("float")
                        .HasComment("The cost of travel which is calculated from distance and gas price");

                    b.Property<int>("TravelTime")
                        .HasColumnType("int")
                        .HasComment("The time it takes to go to the town from given location");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasComment("Zone in which town is located");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Towns");

                    b.HasComment("Where teams and referees are located and matches are played");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 0.0,
                            Name = "Плевен",
                            TravelCost = 0.0,
                            TravelTime = 0,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 2,
                            Distance = 0.0,
                            Name = "Трънчовица",
                            TravelCost = 0.0,
                            TravelTime = 0,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 3,
                            Distance = 0.0,
                            Name = "Гулянци",
                            TravelCost = 0.0,
                            TravelTime = 0,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 4,
                            Distance = 0.0,
                            Name = "Белене",
                            TravelCost = 0.0,
                            TravelTime = 0,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 5,
                            Distance = 0.0,
                            Name = "Гривица",
                            TravelCost = 0.0,
                            TravelTime = 0,
                            ZoneId = 4
                        });
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Name of the zone");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasComment("Zone that is part of region in the country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Плевен Изток"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Плевен Запад"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Плевен Център"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Плевенска Област"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Match", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Division", "Division")
                        .WithMany("Matches")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Town", "Town")
                        .WithMany("Matches")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.TeamSeason", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId", "SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.TeamSeason", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId", "SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Division");

                    b.Navigation("HomeTeam");

                    b.Navigation("Town");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Message", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Referee", "Author")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.RefereeSquad", "RefereeSquad")
                        .WithMany("Messages")
                        .HasForeignKey("RefereeSquadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("RefereeSquad");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.PlayerTeamSeason", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Player", "Player")
                        .WithMany("PlayerTeamsSeasons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.TeamSeason", "TeamSeason")
                        .WithMany("TeamSeasonPlayers")
                        .HasForeignKey("TeamId", "SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Referee", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Town", "Town")
                        .WithMany("Referees")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.ApplicationUser", "User")
                        .WithOne("Referee")
                        .HasForeignKey("FootballRefereeManagementSystem.Data.Models.Referee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.RefereeDivision", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Division", "Division")
                        .WithMany("DivisionReferees")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Referee", "Referee")
                        .WithMany("RefereeDivisions")
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.RefereeSquad", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Referee", "Delegate")
                        .WithMany("DelegateRefereeSquads")
                        .HasForeignKey("DelegateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Referee", "FirstAssistantReferee")
                        .WithMany("FirstAssistantRefereeSquads")
                        .HasForeignKey("FirstAssistantRefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Referee", "MainReferee")
                        .WithMany("MainRefereeSquads")
                        .HasForeignKey("MainRefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Match", "Match")
                        .WithOne("RefereeSquad")
                        .HasForeignKey("FootballRefereeManagementSystem.Data.Models.RefereeSquad", "MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Referee", "SecondAssistantReferee")
                        .WithMany("SecondAssistantRefereeSquads")
                        .HasForeignKey("SecondAssistantRefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delegate");

                    b.Navigation("FirstAssistantReferee");

                    b.Navigation("MainReferee");

                    b.Navigation("Match");

                    b.Navigation("SecondAssistantReferee");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Team", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Town", "Town")
                        .WithMany("Teams")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.TeamSeason", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Division", "Division")
                        .WithMany("TeamsSeasons")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Manager", "Manager")
                        .WithMany("TeamsSeasons")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Season", "Season")
                        .WithMany("SeasonTeams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Team", "Team")
                        .WithMany("TeamSeasons")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Manager");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Town", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.Zone", "Zone")
                        .WithMany("Towns")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballRefereeManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FootballRefereeManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Referee");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Division", b =>
                {
                    b.Navigation("DivisionReferees");

                    b.Navigation("Matches");

                    b.Navigation("TeamsSeasons");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Manager", b =>
                {
                    b.Navigation("TeamsSeasons");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Match", b =>
                {
                    b.Navigation("RefereeSquad");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Player", b =>
                {
                    b.Navigation("PlayerTeamsSeasons");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Referee", b =>
                {
                    b.Navigation("DelegateRefereeSquads");

                    b.Navigation("FirstAssistantRefereeSquads");

                    b.Navigation("MainRefereeSquads");

                    b.Navigation("Messages");

                    b.Navigation("RefereeDivisions");

                    b.Navigation("SecondAssistantRefereeSquads");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.RefereeSquad", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Season", b =>
                {
                    b.Navigation("SeasonTeams");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Team", b =>
                {
                    b.Navigation("TeamSeasons");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.TeamSeason", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("TeamSeasonPlayers");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Town", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Referees");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballRefereeManagementSystem.Data.Models.Zone", b =>
                {
                    b.Navigation("Towns");
                });
#pragma warning restore 612, 618
        }
    }
}
